### ISSUE TITLE
a problem with dependency on solidus frontend

### ISSUE THREAD

**Issue by bosskovic** [solidusio-contrib/solidus_virtual_gift_card#38]
Hi,

in the gemspec there is a dependency on solidus, and solidus includes backend, frontend, core and api.
This is a problem when you do not want frontend gem added.

Would it be possible to replace the dependency on solidus with several dependencies on backend, core, api or whatever the gem depends on, but without frontend, something like here:

https://github.com/Xpitality/solidus_virtual_gift_card/blob/master/solidus_virtual_gift_card.gemspec#L20

Or if you know of any way of not having frontend included from solidus, that would be great too.

Thanks!

**Comment by adammathys** [comment]
I don't see why not. This extension doesn't currently have any hooks into frontend so it would be pretty reasonable to remove it as a dependency.

**Comment by bosskovic** [comment]
ok, should I make a pull request? I already have those changes in a forked repo, but there are also some additions to .gitignore, so if that's a problem, I could rebase and make a fresh PR with a single commit altering only gemspec?

**Comment by bosskovic** [comment]
Hi. Any news on this one? Is there anything I can do to speed up it's adoption?
