### ISSUE TITLE
Solidus dependency out of date

### ISSUE THREAD

**Issue by ollieh-m** [solidusio-contrib/solidus_virtual_gift_card#43]
Thanks for building this very helpful extension!

Are you still supporting it? Currently the gemspec specifies a dependency on `"solidus", "~> 1.2.0"`, which is a major version out. 

I'm wondering if that's deliberate? Do you know if this extension should work with Solidus 2.3? 

Many thanks

**Comment by aldesantis** [comment]
Now up to date and compatible with Solidus 2.5 -> master.
