### ISSUE TITLE
Prepare Solidus Virtual Gift Card for Solidus 3.0

### ISSUE THREAD

**Issue by kennyadsl** [solidusio-contrib/solidus_virtual_gift_card#80]
Update this extension so that it works with Solidus 3.0 by making sure the specs pass.

**Comment by Arunailae** [comment]
Can u please give me a site

**Comment by kennyadsl** [comment]
> Can u please give me a site

@Arunailae hello. What do you mean?

**Comment by Arunailae** [comment]
Good morning

Please I need a site I can get a free gift card to feed myself up

**Comment by Arunailae** [comment]
Good morning Sir

I need your help about the works U do Sir I will be grateful you teach me
some of works I can be perfect a bit to work on my own build a good future
for myself protect the family as well
